### ISSUE TITLE
SwiftUI Tutorial

### ISSUE THREAD

**Issue by daniellevass** [codebar/ios-tutorials#16]
It'd be super nice to have a swiftui tutorial to help people build a cookie clicker!

**Comment by Abizern** [comment]
I'll take a stab at this.

**Comment by daniellevass** [comment]
Let me know if you wanna collaborate on this at all @Abizern - i've been learning some swiftui over the past few weeks at work too :D

**Comment by aabolade** [comment]
+1 with helping, I just finished a SwiftUI project at work. Although less confident about using JavaScript/React to get it on here 😨

**Comment by Abizern** [comment]
Thanks!

I've started a branch on my fork of this repo. I'm going to re-create the current app in SwitUI with relevant explanations.
